//! Parameter lists for the builtin functions, as dart-sass 1.103.1 declares them.
//!
//! Each entry is copied from dart-sass 1.103.1 (`lib/src/functions/*.dart`, and
//! `lib/src/visitor/async_evaluate.dart` for the `sass:meta` functions the
//! evaluator defines). A function with several entries is overloaded: the
//! first list the call matches is used, and otherwise the closest one, which
//! is what dart-sass's `BuiltInCallable.callbackFor` does.
//!
//! The builtins read their arguments by position, so without these lists an
//! unknown named argument could not be rejected and a named argument bound to
//! a parameter after a rest-like read could not be found.

/// The parameter lists of the global function `name`, if it is a builtin.
pub(crate) fn global(name: &str) -> Option<&'static [&'static str]> {
    Some(match name {
        "abs" => &["$number"],
        "adjust-color" => &["$color, $kwargs..."],
        "adjust-hue" => &["$color, $degrees"],
        "alpha" => &["$color", "$args..."],
        "append" => &["$list, $val, $separator: auto"],
        "blue" => &["$color"],
        "call" => &["$function, $args..."],
        "ceil" => &["$number"],
        "change-color" => &["$color, $kwargs..."],
        "color" => &["$description"],
        "comparable" => &["$number1, $number2"],
        "complement" => &["$color, $space: null"],
        "content-exists" => &[""],
        "darken" => &["$color, $amount"],
        "desaturate" => &["$color, $amount"],
        "fade-in" => &["$color, $amount"],
        "fade-out" => &["$color, $amount"],
        "feature-exists" => &["$feature"],
        "floor" => &["$number"],
        "function-exists" => &["$name, $module: null"],
        "get-function" => &["$name, $css: false, $module: null"],
        "global-variable-exists" => &["$name, $module: null"],
        "grayscale" => &["$color"],
        "green" => &["$color"],
        "hsl" => &[
            "$hue, $saturation, $lightness, $alpha",
            "$hue, $saturation, $lightness",
            "$hue, $saturation",
            "$channels",
        ],
        "hsla" => &[
            "$hue, $saturation, $lightness, $alpha",
            "$hue, $saturation, $lightness",
            "$hue, $saturation",
            "$channels",
        ],
        "hue" => &["$color"],
        "hwb" => &["$channels"],
        "ie-hex-str" => &["$color"],
        "if" => &["$condition, $if-true, $if-false"],
        "index" => &["$list, $value"],
        "inspect" => &["$value"],
        "invert" => &["$color, $weight: 100%, $space: null"],
        "is-bracketed" => &["$list"],
        "is-superselector" => &["$super, $sub"],
        "join" => &["$list1, $list2, $separator: auto, $bracketed: auto"],
        "keywords" => &["$args"],
        "lab" => &["$channels"],
        "lch" => &["$channels"],
        "length" => &["$list"],
        "lighten" => &["$color, $amount"],
        "lightness" => &["$color"],
        "list-separator" => &["$list"],
        "map-get" => &["$map, $key, $keys..."],
        "map-has-key" => &["$map, $key, $keys..."],
        "map-keys" => &["$map"],
        "map-merge" => &["$map1, $map2", "$map1, $args..."],
        "map-remove" => &["$map", "$map, $key, $keys..."],
        "map-values" => &["$map"],
        "max" => &["$numbers..."],
        "min" => &["$numbers..."],
        "mix" => &["$color1, $color2, $weight: 50%, $method: null"],
        "mixin-exists" => &["$name, $module: null"],
        "nth" => &["$list, $n"],
        "oklab" => &["$channels"],
        "oklch" => &["$channels"],
        "opacify" => &["$color, $amount"],
        "opacity" => &["$color"],
        "percentage" => &["$number"],
        "quote" => &["$string"],
        "random" => &["$limit: null"],
        "red" => &["$color"],
        "rgb" => &[
            "$red, $green, $blue, $alpha",
            "$red, $green, $blue",
            "$color, $alpha",
            "$channels",
        ],
        "rgba" => &[
            "$red, $green, $blue, $alpha",
            "$red, $green, $blue",
            "$color, $alpha",
            "$channels",
        ],
        "round" => &["$number"],
        "saturate" => &["$amount", "$color, $amount"],
        "saturation" => &["$color"],
        "scale-color" => &["$color, $kwargs..."],
        "selector-append" => &["$selectors..."],
        "selector-extend" => &["$selector, $extendee, $extender"],
        "selector-nest" => &["$selectors..."],
        "selector-parse" => &["$selector"],
        "selector-replace" => &["$selector, $original, $replacement"],
        "selector-unify" => &["$selector1, $selector2"],
        "set-nth" => &["$list, $n, $value"],
        "simple-selectors" => &["$selector"],
        "str-index" => &["$string, $substring"],
        "str-insert" => &["$string, $insert, $index"],
        "str-length" => &["$string"],
        "str-slice" => &["$string, $start-at, $end-at: -1"],
        "to-lower-case" => &["$string"],
        "to-upper-case" => &["$string"],
        "transparentize" => &["$color, $amount"],
        "type-of" => &["$value"],
        "unique-id" => &[""],
        "unit" => &["$number"],
        "unitless" => &["$number"],
        "unquote" => &["$string"],
        "variable-exists" => &["$name"],
        "zip" => &["$lists..."],
        _ => return None,
    })
}

/// The parameter lists of `name` in the builtin module `module` (such as
/// `"map"` for `sass:map`), if it is one.
pub(crate) fn module(module: &str, name: &str) -> Option<&'static [&'static str]> {
    Some(match (module, name) {
        ("color", "adjust") => &["$color, $kwargs..."],
        ("color", "alpha") => &["$color", "$args..."],
        ("color", "blackness") => &["$color"],
        ("color", "blue") => &["$color"],
        ("color", "change") => &["$color, $kwargs..."],
        ("color", "channel") => &["$color, $channel, $space: null"],
        ("color", "complement") => &["$color, $space: null"],
        ("color", "grayscale") => &["$color"],
        ("color", "green") => &["$color"],
        ("color", "hue") => &["$color"],
        ("color", "hwb") => &["$hue, $whiteness, $blackness, $alpha: 1", "$channels"],
        ("color", "ie-hex-str") => &["$color"],
        ("color", "invert") => &["$color, $weight: 100%, $space: null"],
        ("color", "is-in-gamut") => &["$color, $space: null"],
        ("color", "is-legacy") => &["$color"],
        ("color", "is-missing") => &["$color, $channel"],
        ("color", "is-powerless") => &["$color, $channel, $space: null"],
        ("color", "lightness") => &["$color"],
        ("color", "mix") => &["$color1, $color2, $weight: 50%, $method: null"],
        ("color", "opacity") => &["$color"],
        ("color", "red") => &["$color"],
        ("color", "same") => &["$color1, $color2"],
        ("color", "saturation") => &["$color"],
        ("color", "scale") => &["$color, $kwargs..."],
        ("color", "space") => &["$color"],
        ("color", "to-gamut") => &["$color, $space: null, $method: null"],
        ("color", "to-space") => &["$color, $space"],
        ("color", "whiteness") => &["$color"],
        ("list", "append") => &["$list, $val, $separator: auto"],
        ("list", "index") => &["$list, $value"],
        ("list", "is-bracketed") => &["$list"],
        ("list", "join") => &["$list1, $list2, $separator: auto, $bracketed: auto"],
        ("list", "length") => &["$list"],
        ("list", "nth") => &["$list, $n"],
        ("list", "separator") => &["$list"],
        ("list", "set-nth") => &["$list, $n, $value"],
        ("list", "slash") => &["$elements..."],
        ("list", "zip") => &["$lists..."],
        ("map", "deep-merge") => &["$map1, $map2"],
        ("map", "deep-remove") => &["$map, $key, $keys..."],
        ("map", "get") => &["$map, $key, $keys..."],
        ("map", "has-key") => &["$map, $key, $keys..."],
        ("map", "keys") => &["$map"],
        ("map", "merge") => &["$map1, $map2", "$map1, $args..."],
        ("map", "remove") => &["$map", "$map, $key, $keys..."],
        ("map", "set") => &["$map, $key, $value", "$map, $args..."],
        ("map", "values") => &["$map"],
        ("math", "abs") => &["$number"],
        ("math", "acos") => &["$number"],
        ("math", "asin") => &["$number"],
        ("math", "atan") => &["$number"],
        ("math", "atan2") => &["$y, $x"],
        ("math", "ceil") => &["$number"],
        ("math", "clamp") => &["$min, $number, $max"],
        ("math", "compatible") => &["$number1, $number2"],
        ("math", "cos") => &["$number"],
        ("math", "div") => &["$number1, $number2"],
        ("math", "floor") => &["$number"],
        ("math", "hypot") => &["$numbers..."],
        ("math", "is-unitless") => &["$number"],
        ("math", "log") => &["$number, $base: null"],
        ("math", "max") => &["$numbers..."],
        ("math", "min") => &["$numbers..."],
        ("math", "percentage") => &["$number"],
        ("math", "pow") => &["$base, $exponent"],
        ("math", "random") => &["$limit: null"],
        ("math", "round") => &["$number"],
        ("math", "sin") => &["$number"],
        ("math", "sqrt") => &["$number"],
        ("math", "tan") => &["$number"],
        ("math", "unit") => &["$number"],
        ("meta", "accepts-content") => &["$mixin"],
        ("meta", "calc-args") => &["$calc"],
        ("meta", "calc-name") => &["$calc"],
        ("meta", "call") => &["$function, $args..."],
        ("meta", "content-exists") => &[""],
        ("meta", "feature-exists") => &["$feature"],
        ("meta", "function-exists") => &["$name, $module: null"],
        ("meta", "get-function") => &["$name, $css: false, $module: null"],
        ("meta", "get-mixin") => &["$name, $module: null"],
        ("meta", "global-variable-exists") => &["$name, $module: null"],
        ("meta", "inspect") => &["$value"],
        ("meta", "keywords") => &["$args"],
        ("meta", "mixin-exists") => &["$name, $module: null"],
        ("meta", "module-functions") => &["$module"],
        ("meta", "module-mixins") => &["$module"],
        ("meta", "module-variables") => &["$module"],
        ("meta", "type-of") => &["$value"],
        ("meta", "variable-exists") => &["$name"],
        ("selector", "append") => &["$selectors..."],
        ("selector", "extend") => &["$selector, $extendee, $extender"],
        ("selector", "is-superselector") => &["$super, $sub"],
        ("selector", "nest") => &["$selectors..."],
        ("selector", "parse") => &["$selector"],
        ("selector", "replace") => &["$selector, $original, $replacement"],
        ("selector", "simple-selectors") => &["$selector"],
        ("selector", "unify") => &["$selector1, $selector2"],
        ("string", "index") => &["$string, $substring"],
        ("string", "insert") => &["$string, $insert, $index"],
        ("string", "length") => &["$string"],
        ("string", "quote") => &["$string"],
        ("string", "slice") => &["$string, $start-at, $end-at: -1"],
        ("string", "split") => &["$string, $separator, $limit: null"],
        ("string", "to-lower-case") => &["$string"],
        ("string", "to-upper-case") => &["$string"],
        ("string", "unique-id") => &[""],
        ("string", "unquote") => &["$string"],
        _ => return None,
    })
}
