[package]
name = "accent-sass-macro"
version = "0.14.0"
edition = "2024"
description = "Internal implementation of the accent_sass::include! macro"
readme = "README.md"
license = "MIT"
categories = ["web-programming"]
keywords = ["scss", "sass", "css", "web"]
repository = "https://github.com/zoosky/accent-sass"
authors = [
    "Connor Skees <39542938+ConnorSkees@users.noreply.github.com>",
    "Zoo Sky <127824+zoosky@users.noreply.github.com>",
]
include = ["src", "Cargo.toml", "README.md", "LICENSE"]
rust-version = "1.96.1"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", default-features = false }
accent_sass_compiler = { path = "../compiler", version = "=0.14.0" }
quote = { version = "1.0.23", default-features = false }

[features]
nightly = []
